apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-server-config
data:
  mcpserver.yaml: |
    server:
      transport: http
      port: 8089
      host: "0.0.0.0"    
    tools:
      - path: "custom_tools.echo.pancakes"
        name: "pancakes_tool"

  echo.py: |
    from fastmcp import FastMCP
    def pancakes(name: str = "Me") -> str:
        return f"Pancakes for {name} ğŸ¥"
