name: build-deploy mcpserver

on:
  pull_request: {}
  release:
    types: [published]
  push:
    branches:
    - main

jobs:
  build-arm:
    if: (github.event_name != 'pull_request')
    runs-on: ubuntu-latest
    name: make and build arm
    env:
      container: ghcr.io/converged-computing/mcp-server
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Add custom buildx ARM builder
      run: |
       docker buildx create --name armbuilder
       docker buildx use armbuilder
       docker buildx inspect --bootstrap

    - name: Build Container
      run: make arm

    - name: Tag Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container }}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}

    - name: Deploy Container
      run: make push

  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    name: build
    env:
      container: ghcr.io/converged-computing/mcp-server
    steps:
    - uses: actions/checkout@v4
    - name: Build Container
      run: make
    - name: Tag Release Image
      if: (github.event_name == 'release')
      run: |
        tag=${GITHUB_REF#refs/tags/}
        echo "Tagging and releasing ${{ env.container }}:${tag}"
        docker tag ${{ env.container }}:latest ${{ env.container }}:${tag}

    - name: GHCR Login
      if: (github.event_name != 'pull_request')
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy Container
      if: (github.event_name != 'pull_request')
      run: make push
